# .github/workflows/update_editais.yml

name: Atualizador Automático de Editais

# Gatilhos: Como a ação é iniciada
on:
  # 1. Permite rodar manualmente pela aba "Actions" do GitHub
  workflow_dispatch:
  
  # 2. Agenda a execução automática todos os dias às 3:00 AM (horário UTC)
  schedule:
    - cron: '0 3 * * *'

# CORREÇÃO: Adiciona permissões para que a Action possa escrever no repositório.
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Baixa o código do seu repositório para a máquina virtual da Action
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instala as ferramentas que o robô precisa (definidas no requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Passo 4: Roda o robô para buscar os editais e criar o arquivo editais.json
      - name: Run scraper to fetch data
        run: python scraper.py
        
      # Passo 5: Salva (faz commit) do novo arquivo editais.json no seu repositório
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualização automática de editais"
          file_pattern: editais.json
